spring.application.name=shajara

spring.datasource.url=jdbc:postgresql://shajara-db.cgb4ic8kqcjs.us-east-1.rds.amazonaws.com:5432/shajara_db
spring.datasource.username=postgres
spring.datasource.password=jamashkam766
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



server.domain=http://3.95.10.38:8080



# Server port va tashqi kirish uchun
server.port=8080
server.address=0.0.0.0

#spring.mail.username=jamshidbek.madaminov.04@mail.ru
#spring.mail.password=BzdZDLEaaSyPZ5xXEpfB
