spring.application.name=shajara

spring.datasource.url=jdbc:postgresql://localhost:5432/shajara
spring.datasource.username=postgres
spring.datasource.password=jamshid77
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



###########################################
#        EMAIL
###########################################
spring.mail.host=smtp.mail.ru
spring.mail.port=465
spring.mail.username=jamshidbek.madaminov.04@mail.ru
spring.mail.password=BzdZDLEaaSyPZ5xXEpfB
spring.mail.protocol=smtps
server.domain=http://localhost:8080

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=50000
spring.mail.properties.mail.smtp.timeout=50000
spring.mail.properties.mail.smtp.writetimeout=50000


#spring.mail.username=jamshidbek.madaminov.04@mail.ru
#spring.mail.password=BzdZDLEaaSyPZ5xXEpfB
